version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 18
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      # - echo testing...
      - echo building...
      - ng build --configuration=production
  post_build:
    commands:
      - mv appspec.yml ./dist/jamesbond
      - mv scripts ./dist/jamesbond
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/jamesbond